version: '2'

services:
  app:
    image: timjong93/blam2:latest
    ports:
      - '1337:3000'
    depends_on:
      - mongo
    environment:
      ROOT_URL: http://blam.tjongsma.nl
      MONGO_URL: mongodb://mongo:27017/blam
      PORT: 3000

  mongo:
    image: mongo:latest
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db

volumes:
  data:
